#!/usr/bin/env python3
"""Regenerate docs/demo/dashboard.html - the analyst dashboard as an offline snapshot.

Takes the HTML that `python main.py serve` returns (same function, so it cannot drift from the real
UI) and inlines the responses of the five data endpoints, which are plain reads of cases/, traces/,
benchmark/ and monitoring/. The result opens from disk with no server, no dataset and no API key.

    python scripts/build_dashboard_snapshot.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "demo" / "dashboard.html"


def api_payloads() -> dict:
    api: dict = {}
    cases = sorted((ROOT / "cases").glob("HHG-*.json"))
    api["/api/cases"] = [
        {"case_id": d["case_id"], "verdict": d["case"]["verdict"], "probability": d["case"]["fraud_probability"],
         "pattern": d["case"]["pattern"], "status": d["case"]["status"], "exposure": d["case"]["exposure_usd"],
         "sar_filed": d["sar"]["file"], "tool_calls": d["tool_calls"], "latency_s": d["latency_s"]}
        for d in (json.loads(p.read_text()) for p in cases)]
    for p in cases:
        api[f"/api/cases/{p.stem}"] = json.loads(p.read_text())
    for p in sorted((ROOT / "traces").glob("HHG-*.json")):
        api[f"/api/traces/{p.stem}"] = json.loads(p.read_text())
    for name in ("backtest", "case_backtest"):
        f = ROOT / "benchmark" / f"{name}.json"
        if f.exists():
            api.setdefault("/api/benchmark", {})[name] = json.loads(f.read_text())
    f = ROOT / "monitoring" / "alerts.json"
    api["/api/monitoring"] = json.loads(f.read_text()) if f.exists() else {"alerts": []}
    f = ROOT / "evidence" / "tg_live_check.json"
    api["/api/graph/stats"] = json.loads(f.read_text()).get("stats", {}) if f.exists() else {}
    return api


def main() -> None:
    sys.path.insert(0, str(ROOT))
    try:
        from src.ui.app import get_dashboard_html
        html = get_dashboard_html()
    except Exception as e:  # fastapi not installed - the snapshot is a demo artefact, not a gate
        sys.exit(f"needs the ui extra (`pip install -e '.[ui]'`): {e}")

    blob = json.dumps(api_payloads()).replace("</", "<\\/")
    shim = (
        "<script>const __API=" + blob + ";"
        "const __norm=u=>{const s=String(u).split('?')[0];"
        "return __API[s]!==undefined?__API[s]:__API[s.replace(/\\/$/,'')]};\n"
        "window.fetch=(u)=>{const d=__norm(u);return Promise.resolve(new Response("
        "JSON.stringify(d===undefined?{}:d),"
        "{status:d===undefined?404:200,headers:{'Content-Type':'application/json'}}))};</script>"
    )
    html = html.replace("</head>", shim + "\n</head>", 1)
    html = html.replace("<title>Fraud Investigation Agent — TigerGraph</title>",
                        "<title>Fraud Investigation Agent — offline snapshot</title>")
    html = html.replace(
        "<body>",
        "<body>\n<!-- Offline snapshot of `python main.py serve`, generated by "
        "scripts/build_dashboard_snapshot.py from cases/, traces/, benchmark/, monitoring/ and "
        "evidence/. Same page, same data, no server. -->", 1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html)
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size/1024:.0f} KB, "
          f"{len(api_payloads()['/api/cases'])} cases, {len(api_payloads()['/api/monitoring'].get('alerts', []))} alerts)")


if __name__ == "__main__":
    main()
